# ======================================================================
# Cargo Configuration for SSL Certificate Issues
# ======================================================================

# Network settings - use git CLI for fetching
[net]
git-fetch-with-cli = true
retry = 10

# Disable SSL verification for the crates.io registry
[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
# These settings were causing warnings but are necessary for older cargo versions
# protocol = "sparse"
# ssl-verify = false
